/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CenariosRouteImport } from './routes/cenarios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtualizarRouteImport } from './routes/atualizar'
import { Route as IndexRouteImport } from './routes/index'

const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CenariosRoute = CenariosRouteImport.update({
  id: '/cenarios',
  path: '/cenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarRoute = AtualizarRouteImport.update({
  id: '/atualizar',
  path: '/atualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/auth': typeof AuthRoute
  '/cenarios': typeof CenariosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/auth': typeof AuthRoute
  '/cenarios': typeof CenariosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atualizar': typeof AtualizarRoute
  '/auth': typeof AuthRoute
  '/cenarios': typeof CenariosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizar'
    | '/auth'
    | '/cenarios'
    | '/configuracoes'
    | '/historico'
    | '/onboarding'
    | '/privacidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar'
    | '/auth'
    | '/cenarios'
    | '/configuracoes'
    | '/historico'
    | '/onboarding'
    | '/privacidade'
  id:
    | '__root__'
    | '/'
    | '/atualizar'
    | '/auth'
    | '/cenarios'
    | '/configuracoes'
    | '/historico'
    | '/onboarding'
    | '/privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtualizarRoute: typeof AtualizarRoute
  AuthRoute: typeof AuthRoute
  CenariosRoute: typeof CenariosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenarios': {
      id: '/cenarios'
      path: '/cenarios'
      fullPath: '/cenarios'
      preLoaderRoute: typeof CenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar': {
      id: '/atualizar'
      path: '/atualizar'
      fullPath: '/atualizar'
      preLoaderRoute: typeof AtualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtualizarRoute: AtualizarRoute,
  AuthRoute: AuthRoute,
  CenariosRoute: CenariosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
